In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from config import DATA_PATH , CLEAN_DATA_PATH , DASHBOARD_Pics_PATH

In [2]:
df = pd.read_csv(DATA_PATH)

In [3]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   str
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), str(24)
memory usage: 2.9 MB

In [5]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [6]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isna().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [9]:
objects_col = df.select_dtypes(include='str')
for column in objects_col:
    print(f'Column {column} values:{df[column].unique()}')
    print(f'='*10)

Column CustomerID values:<ArrowStringArray>
['3668-QPYBK', '9237-HQITU', '9305-CDSKC', '7892-POOKP', '0280-XJGEX',
 '4190-MFLUW', '8779-QRDMV', '1066-JKSGK', '6467-CHFZW', '8665-UTDHZ',
 ...
 '0871-OPBXW', '3605-JISKB', '9767-FFLEM', '8456-QDAVC', '7750-EYXWZ',
 '2569-WGERO', '6840-RESVB', '2234-XADUH', '4801-JZAZL', '3186-AJIEK']
Length: 7043, dtype: str
==========
Column Country values:<ArrowStringArray>
['United States']
Length: 1, dtype: str
==========
Column State values:<ArrowStringArray>
['California']
Length: 1, dtype: str
==========
Column City values:<ArrowStringArray>
[    'Los Angeles',   'Beverly Hills', 'Huntington Park',         'Lynwood',
  'Marina Del Rey',       'Inglewood',    'Santa Monica',        'Torrance',
        'Whittier',        'La Habra',
 ...
      'Janesville',      'Litchfield',        'Loyalton',        'Madeline',
    'Markleeville',         'Milford',         'Calpine',        'Standish',
        'Tulelake',  'Olympic Valley']
Length: 1129, dtype: str
==========
Column Lat Long values:<ArrowStringArray>
['33.964131, -118.272783',  '34.059281, -118.30742', '34.048013, -118.293953',
 '34.062125, -118.315709', '34.039224, -118.266293', '34.066367, -118.309868',
  '34.02381, -118.156582', '34.066303, -118.435479', '34.099869, -118.326843',
 '34.089953, -118.294824',
 ...
 '40.294034, -120.512622', '40.507272, -120.338228', '39.637471, -120.226338',
 '41.042003, -120.506086',  '38.735789, -119.85798', '40.181279, -120.392967',
 '39.672813, -120.456699', '40.346634, -120.386422', '41.813521, -121.492666',
 '39.191797, -120.212401']
Length: 1652, dtype: str
==========
Column Gender values:<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
==========
Column Senior Citizen values:<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
==========
Column Partner values:<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
==========
Column Dependents values:<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
==========
Column Phone Service values:<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
==========
Column Multiple Lines values:<ArrowStringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str
==========
Column Internet Service values:<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
==========
Column Online Security values:<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
==========
Column Online Backup values:<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
==========
Column Device Protection values:<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
==========
Column Tech Support values:<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
==========
Column Streaming TV values:<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
==========
Column Streaming Movies values:<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
==========
Column Contract values:<ArrowStringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str
==========
Column Paperless Billing values:<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
==========
Column Payment Method values:<ArrowStringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
==========
Column Total Charges values:<ArrowStringArray>
[ '108.15',  '151.65',   '820.5', '3046.05',  '5036.3',  '528.35',   '39.65',
   '20.15', '4749.15',    '30.2',
 ...
   '39.25',  '3316.1', '2625.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',
  '7362.9',  '346.45',  '6844.5']
Length: 6531, dtype: str
==========
Column Churn Label values:<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
==========
Column Churn Reason values:<ArrowStringArray>
[             'Competitor made better offer',
                                     'Moved',
             'Competitor had better devices',
 'Competitor offered higher download speeds',
              'Competitor offered more data',
                            'Price too high',
                   'Product dissatisfaction',
                   'Service dissatisfaction',
           'Lack of self-service on Website',
                       'Network reliability',
                 'Limited range of services',
  'Lack of affordable download/upload speed',
                     'Long distance charges',
                        'Extra data charges',
                                'Don't know',
          'Poor expertise of online support',
           'Poor expertise of phone support',
              'Attitude of service provider',
                'Attitude of support person',
                                  'Deceased',
                                         nan]
Length: 21, dtype: str
==========

In [10]:
removed_col = ['CustomerID','Count','Country','State','Lat Long','Latitude','Longitude','Zip Code','Churn Score']
df = df.drop(columns=removed_col)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   str
 1   Gender             7043 non-null   str
 2   Senior Citizen     7043 non-null   str
 3   Partner            7043 non-null   str
 4   Dependents         7043 non-null   str
 5   Tenure Months      7043 non-null   int64
 6   Phone Service      7043 non-null   str
 7   Multiple Lines     7043 non-null   str
 8   Internet Service   7043 non-null   str
 9   Online Security    7043 non-null   str
 10  Online Backup      7043 non-null   str
 11  Device Protection  7043 non-null   str
 12  Tech Support       7043 non-null   str
 13  Streaming TV       7043 non-null   str
 14  Streaming Movies   7043 non-null   str
 15  Contract           7043 non-null   str
 16  Paperless Billing  7043 non-null   str
 17  Payment Method     7043 non-null   str
 18  Monthly Charges    7043 non-null   float64
 19  Total Charges      7043 non-null   str
 20  Churn Label        7043 non-null   str
 21  Churn Value        7043 non-null   int64
 22  CLTV               7043 non-null   int64
 23  Churn Reason       1869 non-null   str
dtypes: float64(1), int64(3), str(20)
memory usage: 2.1 MB

In [12]:
df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce")

In [13]:
df[df['Total Charges'].isna()].head()

,City,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,...,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,CLTV,Churn Reason
2234,San Bernardino,Female,No,Yes,No,0,No,No phone service,DSL,Yes,...,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No,0,2578,NaN
2438,Independence,Male,No,No,No,0,Yes,No,No,No internet service,...,No internet service,Two year,No,Mailed check,20.25,NaN,No,0,5504,NaN
2568,San Mateo,Female,No,Yes,No,0,Yes,No,DSL,Yes,...,Yes,Two year,No,Mailed check,80.85,NaN,No,0,2048,NaN
2667,Cupertino,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,Two year,No,Mailed check,25.75,NaN,No,0,4950,NaN
2856,Redcrest,Female,No,Yes,No,0,No,No phone service,DSL,Yes,...,No,Two year,No,Credit card (automatic),56.05,NaN,No,0,4740,NaN

In [14]:
print(df['Total Charges'].isna().sum())
df['Total Charges']= df['Total Charges'].fillna(0)
print(df['Total Charges'].isna().sum())

11
0

In [15]:
def save_plot(filename):
    path = os.path.join(DASHBOARD_Pics_PATH, filename)
    plt.tight_layout()
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    
    print(f"Saved: {path}")

In [16]:
objects_col = df.select_dtypes(include='str').drop(columns=['City','Churn Reason']).columns

count_fig , axes = plt.subplots(4,5, figsize=(20,10))
axes = axes.flatten()
for i in range(objects_col.size):
    col_name = objects_col[i]
    sns.countplot(df[col_name], ax=axes[i])
    axes[i].set_title(f'count of {col_name}')

count_fig.tight_layout()
count_fig.show()
save_plot("graph_1")

C:\Users\gaber\AppData\Local\Temp\ipykernel_1944\2065687416.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  count_fig.show()

Saved: Dashboard/Resources/Pics\graph_1

In [17]:
num_col = df.select_dtypes(include='number').columns

hist_fig , axes = plt.subplots(2,3, figsize=(20,10))
axes = axes.flatten()
for i in range(num_col.size):
    col_name = num_col[i]
    sns.histplot(df[col_name], ax=axes[i])
    axes[i].set_title(f'distribuation of {col_name}')

hist_fig.tight_layout()
hist_fig.show()
save_plot('graph_2')

C:\Users\gaber\AppData\Local\Temp\ipykernel_1944\136722724.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  hist_fig.show()

Saved: Dashboard/Resources/Pics\graph_2

In [18]:
box_fig , axes = plt.subplots(2,3, figsize=(20,10))
axes = axes.flatten()
for i in range(num_col.size):
    col_name = num_col[i]
    sns.boxplot(df[col_name], ax=axes[i])
    axes[i].set_title(f'distribuation of {col_name}')

box_fig.tight_layout()
box_fig.show()
save_plot('graph_3')

C:\Users\gaber\AppData\Local\Temp\ipykernel_1944\3401533601.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  box_fig.show()

Saved: Dashboard/Resources/Pics\graph_3

In [19]:
sns.countplot(data=df , x='Churn Label')
save_plot('graph_4')

Saved: Dashboard/Resources/Pics\graph_4

In [20]:
plt.figure(figsize=(6, 4))
df.groupby("Contract")["Churn Value"].mean().sort_values().plot(kind="barh")
plt.title("Churn Rate by Contract Type")
plt.xlabel("Churn Rate")

save_plot('graph_5')

Saved: Dashboard/Resources/Pics\graph_5

In [21]:
plt.figure(figsize=(5, 4))
sns.boxplot(x="Churn Label", y="Monthly Charges", data=df)
plt.title("Monthly Charges by Churn")
save_plot('graph_6')

Saved: Dashboard/Resources/Pics\graph_6

In [22]:
plt.figure(figsize=(6, 4))
df.groupby("Payment Method")["Churn Value"].mean().sort_values().plot(kind="bar")
plt.title("Churn Rate by Contract Type")
plt.xlabel("Payment Method")
save_plot('graph_7')

Saved: Dashboard/Resources/Pics\graph_7

In [23]:
reasons = (df[df["Churn Label"] == "Yes"]["Churn Reason"].value_counts().head(12).sort_values(ascending=False))

sns.barplot(x=reasons.values,y=reasons.index)
save_plot('graph_8')

Saved: Dashboard/Resources/Pics\graph_8

In [24]:
useless_for_models = ['City','Churn Reason','Churn Label']
df = df.drop(columns=useless_for_models)

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             7043 non-null   str
 1   Senior Citizen     7043 non-null   str
 2   Partner            7043 non-null   str
 3   Dependents         7043 non-null   str
 4   Tenure Months      7043 non-null   int64
 5   Phone Service      7043 non-null   str
 6   Multiple Lines     7043 non-null   str
 7   Internet Service   7043 non-null   str
 8   Online Security    7043 non-null   str
 9   Online Backup      7043 non-null   str
 10  Device Protection  7043 non-null   str
 11  Tech Support       7043 non-null   str
 12  Streaming TV       7043 non-null   str
 13  Streaming Movies   7043 non-null   str
 14  Contract           7043 non-null   str
 15  Paperless Billing  7043 non-null   str
 16  Payment Method     7043 non-null   str
 17  Monthly Charges    7043 non-null   float64
 18  Total Charges      7043 non-null   float64
 19  Churn Value        7043 non-null   int64
 20  CLTV               7043 non-null   int64
dtypes: float64(2), int64(3), str(16)
memory usage: 1.8 MB

In [26]:
df.to_csv(CLEAN_DATA_PATH,index=False)